"""Unit tests for GestureEvent (TASK-001, openspec/changes/multimodal-interaction-core)."""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from jarvis.core.events import GestureEvent, VALID_STATES  # noqa: E402


def make_event(**overrides):
    defaults = dict(
        gesture_type="PINCH",
        confidence=0.94,
        timestamp=1000.0,
        source="CAMERA",
        state="ACTIVE",
        hand="RIGHT",
        position=(0.63, 0.41),
        velocity=(0.02, -0.01),
        duration_ms=240,
    )
    defaults.update(overrides)
    return GestureEvent(**defaults)


class GestureEventModelTests(unittest.TestCase):
    def test_valid_event_is_created_with_expected_fields(self):
        event = make_event()
        self.assertEqual(event.gesture_type, "PINCH")
        self.assertEqual(event.hand, "RIGHT")
        self.assertEqual(event.confidence, 0.94)
        self.assertEqual(event.position, (0.63, 0.41))
        self.assertEqual(event.velocity, (0.02, -0.01))
        self.assertEqual(event.duration_ms, 240)
        self.assertEqual(event.source, "CAMERA")
        self.assertEqual(event.state, "ACTIVE")
        self.assertIsNotNone(event.id)

    def test_id_autogenerated_and_unique_when_not_given(self):
        e1, e2 = make_event(), make_event()
        self.assertNotEqual(e1.id, e2.id)

    def test_id_can_be_provided_explicitly(self):
        event = make_event(id="fixed-id-123")
        self.assertEqual(event.id, "fixed-id-123")

    def test_optional_fields_default_to_none_or_empty(self):
        event = GestureEvent(
            gesture_type="FIST",
            confidence=0.8,
            timestamp=1.0,
            source="CAMERA",
            state="DETECTED",
        )
        self.assertIsNone(event.hand)
        self.assertIsNone(event.position)
        self.assertIsNone(event.velocity)
        self.assertIsNone(event.duration_ms)
        self.assertEqual(event.metadata, {})

    def test_event_is_immutable(self):
        event = make_event()
        with self.assertRaises(Exception):
            event.confidence = 0.5


class GestureEventValidationTests(unittest.TestCase):
    def test_confidence_out_of_range_rejected(self):
        with self.assertRaises(ValueError):
            make_event(confidence=1.5)
        with self.assertRaises(ValueError):
            make_event(confidence=-0.1)

    def test_confidence_boundaries_accepted(self):
        make_event(confidence=0.0)
        make_event(confidence=1.0)

    def test_confidence_must_be_numeric(self):
        with self.assertRaises(ValueError):
            make_event(confidence="high")
        with self.assertRaises(ValueError):
            make_event(confidence=True)

    def test_timestamp_required_and_numeric(self):
        with self.assertRaises(ValueError):
            make_event(timestamp=None)
        with self.assertRaises(ValueError):
            make_event(timestamp="not-a-number")

    def test_gesture_type_required(self):
        with self.assertRaises(ValueError):
            make_event(gesture_type="")
        with self.assertRaises(ValueError):
            make_event(gesture_type=None)

    def test_source_required(self):
        with self.assertRaises(ValueError):
            make_event(source="")

    def test_state_must_be_a_known_value(self):
        with self.assertRaises(ValueError):
            make_event(state="NOT_A_REAL_STATE")

    def test_all_documented_states_are_accepted(self):
        for state in VALID_STATES:
            make_event(state=state)  # should not raise

    def test_hand_must_be_string_or_none(self):
        make_event(hand=None)
        with self.assertRaises(ValueError):
            make_event(hand=123)

    def test_position_must_be_pair_of_numbers(self):
        with self.assertRaises(ValueError):
            make_event(position=(0.1,))
        with self.assertRaises(ValueError):
            make_event(position=("a", "b"))

    def test_position_list_is_normalized_to_tuple(self):
        event = make_event(position=[0.1, 0.2])
        self.assertEqual(event.position, (0.1, 0.2))
        self.assertIsInstance(event.position, tuple)

    def test_velocity_must_be_pair_of_numbers(self):
        with self.assertRaises(ValueError):
            make_event(velocity=(1, 2, 3))

    def test_duration_ms_must_be_non_negative(self):
        with self.assertRaises(ValueError):
            make_event(duration_ms=-5)
        make_event(duration_ms=0)

    def test_metadata_must_be_dict(self):
        with self.assertRaises(ValueError):
            make_event(metadata=["not", "a", "dict"])

    def test_id_must_be_non_empty_string_if_provided(self):
        with self.assertRaises(ValueError):
            make_event(id="")
        with self.assertRaises(ValueError):
            make_event(id=42)


if __name__ == "__main__":
    unittest.main()
